apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# helmCharts:
#   - name: synology-csi
#     repo: https://christian-schlichtherle.github.io/synology-csi-chart
#     version: 0.9.8
#     releaseName: synology-csi
#     namespace: synology-csi
#     valuesFile: values.yaml

resources:
  - resources/client-info.yaml
  - https://raw.githubusercontent.com/SynologyOpenSource/synology-csi/v1.1.3/deploy/kubernetes/v1.20/controller.yml
  - https://raw.githubusercontent.com/SynologyOpenSource/synology-csi/v1.1.3/deploy/kubernetes/v1.20/csi-driver.yml
  - https://raw.githubusercontent.com/SynologyOpenSource/synology-csi/v1.1.3/deploy/kubernetes/v1.20/node.yml
  - storage-class-retain.yaml
  - storage-class-delete.yaml

namespace: synology-csi
