apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: flaresolverr
    app.kubernetes.io/name: flaresolverr
  name: flaresolverr
  namespace: media
spec:
  ports:
  - name: main
    port: 8191
    protocol: TCP
    targetPort: 8191
  selector:
    app.kubernetes.io/instance: flaresolverr
    app.kubernetes.io/name: flaresolverr
  type: ClusterIP