apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: media
  name: jellyseer-config-nfs
spec:
  storageClassName: nfs-csi-retain
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
