apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: sonarr 
  repo: https://bananaspliff.github.io/geek-charts
  releaseName: sonarr 
  namespace: media
  valuesFile: values.yaml
