apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-cert
spec:
  secretName: josephang-space-tls
  issuerRef:
    name: letsencrypt-issuer-prd
    kind: ClusterIssuer
  dnsNames:
  - '*.josephang.space'