apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-cert
spec:
  secretName: kopi-quest-tls
  issuerRef:
    name: letsencrypt-issuer-prd
    kind: ClusterIssuer
  dnsNames:
  - '*.kopi.quest'