apiVersion: v1
kind: Service
metadata:
  name: synology-ldap
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.18.154
  ports:
    - name: ldap
      port: 389         # For unencrypted LDAP
      targetPort: 389
      protocol: TCP
    - name: ldaps
      port: 636         # For LDAPS
      targetPort: 636
      protocol: TCP