apiVersion: v1
kind: Service
metadata:
  name: synology-ldap
spec:
  type: ClusterIP
  ports:
    - name: 389-tcp
      port: 389         # For unencrypted LDAP
      targetPort: 389
      protocol: TCP
    - name: 636-tcp
      port: 636         # For LDAPS
      targetPort: 636
      protocol: TCP