apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: media
  name: config
spec:
  storageClassName: nfs-csi-retain
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
