apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: jellyfin
    app.kubernetes.io/name: jellyfin
  name: jellyfin
  namespace: media
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.18.200
  ports:
    - name: main
      port: 8096
      protocol: TCP
      targetPort: 8096
  selector:
    app.kubernetes.io/instance: jellyfin
    app.kubernetes.io/name: jellyfin