apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  url: https://argocd.josephang.space
  configManagementPlugins: |
    - name: kustomize-enable-helm
      generate:
        command: [ "sh", "-c" ]
        args: [ "kustomize build --enable-helm" ]
  dex.config: |
    connectors:
    - config:
        issuer: https://authentik.josephang.space/application/o/argocd/
        redirectURI: https://authentik.josephang.space/callback
        clientID: WkuZi6KqJzYEHcKbnGbmEZtUstdMFpITyRUJeLC7
        clientSecret: $dex.authentik.clientSecret
        insecureEnableGroups: true
        scopes:
          - openid
          - profile
          - email
      name: authentik
      type: oidc
      id: authentik